### PR TITLE
This buffs the strong warrior

### PR DESCRIPTION
**Pull request by Topkinsme**
Part of #6 , Buffing Strong Warrior

### CODE REVIEW

**Comment by Topkinsme** [comment]
This should fix #6 

Close #6

**Comment by 12Metatron** [comment]
i think theres better ways to buff it than making it a stronger alert warrior

**Comment by Topkinsme** [comment]
I think it's a fiar fix since it's a 1-time thing and the long respawn time if you decide to sacrifice the role

**Comment by Topkinsme** [comment]
This buff was unfavoured and will not be done.

**Pull request closed without merging**
