### PR TITLE
Create Scout

### PR DESCRIPTION
**Pull request by 12Metatron**

### CODE REVIEW

**Comment by Topkinsme** [comment]
Is the scouting process itself a visit? If so I disapprove, no reason for an invest role to be a visit yet. If it's not, it sounds good.

**Comment by 12Metatron** [comment]
not a visit, theyre watching from far away with binoculars

**Comment by Topkinsme** [comment]
Alright, Will approve.

**Comment by Topkinsme** [comment]
Thought, I'd recommend adding the scout results to the action order, unless it's unnecessary.

**Pull request merged**
