### PR TITLE
New Buff for Prince required!

### PR DESCRIPTION
**Pull request by TheEighthDeadlySin**
Due to the recent implementation of a new Royalty system and three extra roles (Jack, Queen & Princess) which both replace the King and have an extra ability, the Prince now seems relatively weak in comparison. We need to think of a new buff for the Prince which would balance the current disadvantage of the Prince having no other ability which would also be more appealing to use. Currently I do not know anything we could do to buff the Prince role, however when I do, I will put my ideas in this discussion. Feel free to suggest any ideas you may have that could potentially become the buff for the Prince.

### CODE REVIEW

**Comment by TheEighthDeadlySin** [comment]
In case you are wondering why I did not create a discussion about this instead, for some reason it kept giving me an error each time I tried to create a new discussion about the Prince buff.

**Comment by TheEighthDeadlySin** [comment]
Here is a list of potential buffs that others have suggested (according to Top):

- Prince can change their respawn time every time they die, from a minimum of 2 phases, to a maximum of 6 phases [suggested by Lord of Galaxy]
- Prince can weakly disguise as another team at the start of the game [suggested by Ethan]
- When the Prince becomes the King, every team members' respawn times are reduced (by 1 or 2 phases) [suggested by Jayanna]
- If the Prince is respawning when the King dies, they instantly respawn and become the King. [suggested by Luffy]

My opinion on each potential buff:
- Lord of Galaxy: This ability could be useful, but also seems a bit weaker than the original Prince (seeing how the original Prince always respawned in 2 phases).
- Ethan: This ability seems extremely weak to be honest. Seeing how we normally play a 3 colour faction game (potentially increasing it to 4 if we have enough players), the disguise will likely only affect up to 1/2 teams (the other team which you disguise as will clearly know that you are disguised).
- Jayanna: This ability is either too OP, or completely redundant if your team manages to get the auction item which sets all of your team's respawn times to 2 phases.
- Luffy: This idea seems alright, however will potentially make it clear to the other teams that you were the Prince (making you quite a large target). Seems to be the most balanced with the Queen and Princess abilities at the current moment.

**Comment by Topkinsme** [comment]
In my personal opinion, I liked Luffy's idea the most, as this wouldn't be too much of a buff, but still guarantee that your team can't be instantly wiped which I think is great. About the part where it's revealed, I think that's true, but I don't think it's that big of a deal.

Ethan's buff is decent too, I don't have anything to add, but I don't think it'll be enough to pick it over princess or queen.
Jay's buff is a bit too strong. Maybe it's doable if we make it 1 phase because then it'll also reveal quite a bit of information to the other teams. 
Log's buff is decent, but again it's not as good as a princess or a queen. Might be worth doing tho.

**Comment by TheEighthDeadlySin** [comment]
I kinda moved this to #73 and started brainstorming there instead. So I am going to not talk in here for now, but when we have a buff we all agreed on, I will use this pull request to implement it.

**Comment by Topkinsme** [comment]
Alright.

**Comment by Topkinsme** [comment]
Fixes #73

**Pull request merged**
